name: Rust Build and Test

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:

  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: |
        if ! cargo fmt --all -- --check; then
          echo "::error::Code is not properly formatted. Run 'cargo fmt' to fix."
          exit 0
        fi
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
